package org.goafabric.libraryservice.logic.mapper

import jakarta.enterprise.context.ApplicationScoped
import org.goafabric.libraryservice.controller.dto.Book
import org.goafabric.libraryservice.controller.dto.Student
import org.goafabric.libraryservice.persistence.entity.BookEo
import org.goafabric.libraryservice.persistence.entity.StudentEo
import org.mapstruct.Mapper
import org.mapstruct.factory.Mappers

/**
 * Mapper generated by MapStruct to map Entities to DTOs.
 */
@ApplicationScoped
interface LibraryMapper {
    fun convertStudent(entity: StudentEo): Student
    fun convertBook(entity: BookEo): Book
    
    companion object {
        val INSTANCE = Mappers.getMapper(LibraryMapper::class.java)
    }
}
