#web
quarkus.application.name=container-ui
quarkus.http.port=8081
quarkus.http.io-threads=20

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#openapi
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.store-schema-directory=doc/generated

#tracing
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.log.category."io.opentelemetry.exporter.internal".level=OFF
quarkus.log.category."io.quarkus.opentelemetry.runtime.exporter.otlp.sender".level=OFF

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO

#jacoco
quarkus.jacoco.report=false
