#web
quarkus.application.name=container-ui
quarkus.http.port=8081
quarkus.http.io-threads=20

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO

#jacoco
quarkus.jacoco.report=false
